server:
  port: 8080
#  tomcat:
#    max-threads: 1

#
## logging configuration
#
logging:
  file: logs/app.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(18971){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "[%d] [%-5level] [%thread] [%logger] - [%msg]%n"
  level:
    org.springframework.web: WARN
    org.springframework.security: WARN
    com.asimio: INFO